/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square
// GiftCardActivityClearBalanceReason : Indicates the reason for clearing the balance of a [gift card]($m/GiftCard).
type GiftCardActivityClearBalanceReason string

// List of GiftCardActivityClearBalanceReason
const (
	SUSPICIOUS_ACTIVITY_GiftCardActivityClearBalanceReason GiftCardActivityClearBalanceReason = "SUSPICIOUS_ACTIVITY"
	REUSE_GIFTCARD_GiftCardActivityClearBalanceReason GiftCardActivityClearBalanceReason = "REUSE_GIFTCARD"
	UNKNOWN_REASON_GiftCardActivityClearBalanceReason GiftCardActivityClearBalanceReason = "UNKNOWN_REASON"
)
