/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square
// VendorStatus : The status of the [Vendor]($m/Vendor), whether a [Vendor]($m/Vendor) is active or inactive.
type VendorStatus string

// List of VendorStatus
const (
	ACTIVE_VendorStatus VendorStatus = "ACTIVE"
	INACTIVE_VendorStatus VendorStatus = "INACTIVE"
)
