/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Represents the mapping that associates a loyalty account with a buyer.   Currently, a loyalty account can only be mapped to a buyer by phone number. For more information, see  [Loyalty Overview](https://developer.squareup.com/docs/loyalty/overview).
type LoyaltyAccountMapping struct {
	// The Square-assigned ID of the mapping.
	Id string `json:"id,omitempty"`
	// The timestamp when the mapping was created, in RFC 3339 format.
	CreatedAt string `json:"created_at,omitempty"`
	// The phone number of the buyer, in E.164 format. For example, \"+14155551111\".
	PhoneNumber string `json:"phone_number,omitempty"`
}
