/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Dietary preferences that can be assigned to an `FOOD_AND_BEV` item and its ingredients.
type CatalogItemFoodAndBeverageDetailsDietaryPreference struct {
	Type_ *CatalogItemFoodAndBeverageDetailsDietaryPreferenceType `json:"type,omitempty"`
	StandardName *CatalogItemFoodAndBeverageDetailsDietaryPreferenceStandardDietaryPreference `json:"standard_name,omitempty"`
	// The name of a user-defined custom dietary preference. This should be null if it's a standard dietary preference.
	CustomName string `json:"custom_name,omitempty"`
}
