/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Criteria to filter events by.
type SearchEventsFilter struct {
	// Filter events by event types.
	EventTypes []string `json:"event_types,omitempty"`
	// Filter events by merchant.
	MerchantIds []string `json:"merchant_ids,omitempty"`
	// Filter events by location.
	LocationIds []string `json:"location_ids,omitempty"`
	CreatedAt *TimeRange `json:"created_at,omitempty"`
}
