/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type TenderBuyNowPayLaterDetailsStatus string

// List of TenderBuyNowPayLaterDetailsStatus
const (
	AUTHORIZED_TenderBuyNowPayLaterDetailsStatus TenderBuyNowPayLaterDetailsStatus = "AUTHORIZED"
	CAPTURED_TenderBuyNowPayLaterDetailsStatus TenderBuyNowPayLaterDetailsStatus = "CAPTURED"
	VOIDED_TenderBuyNowPayLaterDetailsStatus TenderBuyNowPayLaterDetailsStatus = "VOIDED"
	FAILED_TenderBuyNowPayLaterDetailsStatus TenderBuyNowPayLaterDetailsStatus = "FAILED"
)
