/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square
// OrderFulfillmentDeliveryDetailsScheduleType : The schedule type of the delivery fulfillment.
type OrderFulfillmentDeliveryDetailsScheduleType string

// List of OrderFulfillmentDeliveryDetailsScheduleType
const (
	SCHEDULED_OrderFulfillmentDeliveryDetailsScheduleType OrderFulfillmentDeliveryDetailsScheduleType = "SCHEDULED"
	ASAP_OrderFulfillmentDeliveryDetailsScheduleType OrderFulfillmentDeliveryDetailsScheduleType = "ASAP"
)
