/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Describes a subscription plan variation. A subscription plan variation represents how the subscription for a product or service is sold. For more information, see [Subscription Plans and Variations](https://developer.squareup.com/docs/subscriptions-api/plans-and-variations).
type CatalogSubscriptionPlanVariation struct {
	// The name of the plan variation.
	Name string `json:"name"`
	// A list containing each [SubscriptionPhase](entity:SubscriptionPhase) for this plan variation.
	Phases []SubscriptionPhase `json:"phases"`
	// The id of the subscription plan, if there is one.
	SubscriptionPlanId string `json:"subscription_plan_id,omitempty"`
	// The day of the month the billing period starts.
	MonthlyBillingAnchorDate int64 `json:"monthly_billing_anchor_date,omitempty"`
	// Whether bills for this plan variation can be split for proration.
	CanProrate bool `json:"can_prorate,omitempty"`
	// The ID of a \"successor\" plan variation to this one. If the field is set, and this object is disabled at all locations, it indicates that this variation is deprecated and the object identified by the successor ID be used in its stead.
	SuccessorPlanVariationId string `json:"successor_plan_variation_id,omitempty"`
}
