/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Describes the ingredient used in a `FOOD_AND_BEV` item.
type CatalogItemFoodAndBeverageDetailsIngredient struct {
	Type_ *CatalogItemFoodAndBeverageDetailsDietaryPreferenceType `json:"type,omitempty"`
	StandardName *CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient `json:"standard_name,omitempty"`
	// The name of a custom user-defined ingredient. This should be null if it's a standard dietary preference.
	CustomName string `json:"custom_name,omitempty"`
}
