/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// CatalogItemFoodAndBeverageDetailsDietaryPreferenceType : The type of dietary preference for the `FOOD_AND_BEV` type of items and integredients.
type CatalogItemFoodAndBeverageDetailsDietaryPreferenceType string

// List of CatalogItemFoodAndBeverageDetailsDietaryPreferenceType
const (
	STANDARD_CatalogItemFoodAndBeverageDetailsDietaryPreferenceType CatalogItemFoodAndBeverageDetailsDietaryPreferenceType = "STANDARD"
	CUSTOM_CatalogItemFoodAndBeverageDetailsDietaryPreferenceType CatalogItemFoodAndBeverageDetailsDietaryPreferenceType = "CUSTOM"
)
