/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Represents a file attached to an [invoice]($m/Invoice).
type InvoiceAttachment struct {
	// The Square-assigned ID of the attachment.
	Id string `json:"id,omitempty"`
	// The file name of the attachment, which is displayed on the invoice.
	Filename string `json:"filename,omitempty"`
	// The description of the attachment, which is displayed on the invoice. This field maps to the seller-defined **Message** field.
	Description string `json:"description,omitempty"`
	// The file size of the attachment in bytes.
	Filesize int32 `json:"filesize,omitempty"`
	// The MD5 hash that was generated from the file contents.
	Hash string `json:"hash,omitempty"`
	// The mime type of the attachment. The following mime types are supported:  image/gif, image/jpeg, image/png, image/tiff, image/bmp, application/pdf.
	MimeType string `json:"mime_type,omitempty"`
	// The timestamp when the attachment was uploaded, in RFC 3339 format.
	UploadedAt string `json:"uploaded_at,omitempty"`
}
