/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Represents a [BulkDeleteLocationCustomAttributes]($e/LocationCustomAttributes/BulkDeleteLocationCustomAttributes) request.
type BulkDeleteLocationCustomAttributesRequest struct {
	// The data used to update the `CustomAttribute` objects. The keys must be unique and are used to map to the corresponding response.
	Values map[string]BulkDeleteLocationCustomAttributesRequestLocationCustomAttributeDeleteRequest `json:"values"`
}
