/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Represents the arguments used to construct a new phase.
type PhaseInput struct {
	// index of phase in total subscription plan
	Ordinal int64 `json:"ordinal"`
	// id of order to be used in billing
	OrderTemplateId string `json:"order_template_id,omitempty"`
}
