/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square
// FulfillmentType : The type of fulfillment.
type FulfillmentType string

// List of FulfillmentType
const (
	PICKUP_FulfillmentType FulfillmentType = "PICKUP"
	SHIPMENT_FulfillmentType FulfillmentType = "SHIPMENT"
	DELIVERY_FulfillmentType FulfillmentType = "DELIVERY"
)
