/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckoutLocationSettingsBranding struct {
	HeaderType *CheckoutLocationSettingsBrandingHeaderType `json:"header_type,omitempty"`
	// The HTML-supported hex color for the button on the checkout page (for example, \"#FFFFFF\").
	ButtonColor string `json:"button_color,omitempty"`
	ButtonShape *CheckoutLocationSettingsBrandingButtonShape `json:"button_shape,omitempty"`
}
