/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type DeviceComponentDetailsCardReaderDetails struct {
	// The version of the card reader.
	Version string `json:"version,omitempty"`
}
