/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square
// ArchivedState : Defines the values for the `archived_state` query expression  used in [SearchCatalogItems]($e/Catalog/SearchCatalogItems)  to return the archived, not archived or either type of catalog items.
type ArchivedState string

// List of ArchivedState
const (
	NOT_ARCHIVED_ArchivedState ArchivedState = "ARCHIVED_STATE_NOT_ARCHIVED"
	ARCHIVED_ArchivedState ArchivedState = "ARCHIVED_STATE_ARCHIVED"
	ALL_ArchivedState ArchivedState = "ARCHIVED_STATE_ALL"
)
