/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SignatureImage struct {
	// The mime/type of the image data. Use `image/png;base64` for png.
	ImageType string `json:"image_type,omitempty"`
	// The base64 representation of the image.
	Data string `json:"data,omitempty"`
}
