/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// The wrapper object for the component entries of a given component type.
type Component struct {
	Type_ *ComponentComponentType `json:"type"`
	ApplicationDetails *DeviceComponentDetailsApplicationDetails `json:"application_details,omitempty"`
	CardReaderDetails *DeviceComponentDetailsCardReaderDetails `json:"card_reader_details,omitempty"`
	BatteryDetails *DeviceComponentDetailsBatteryDetails `json:"battery_details,omitempty"`
	WifiDetails *DeviceComponentDetailsWiFiDetails `json:"wifi_details,omitempty"`
	EthernetDetails *DeviceComponentDetailsEthernetDetails `json:"ethernet_details,omitempty"`
}
