/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckoutMerchantSettingsPaymentMethods struct {
	ApplePay *CheckoutMerchantSettingsPaymentMethodsPaymentMethod `json:"apple_pay,omitempty"`
	GooglePay *CheckoutMerchantSettingsPaymentMethodsPaymentMethod `json:"google_pay,omitempty"`
	CashApp *CheckoutMerchantSettingsPaymentMethodsPaymentMethod `json:"cash_app,omitempty"`
	AfterpayClearpay *CheckoutMerchantSettingsPaymentMethodsAfterpayClearpay `json:"afterpay_clearpay,omitempty"`
}
