/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type CheckoutLocationSettingsPolicy struct {
	// A unique ID to identify the policy when making changes. You must set the UID for policy updates, but it’s optional when setting new policies.
	Uid string `json:"uid,omitempty"`
	// The title of the policy. This is required when setting the description, though you can update it in a different request.
	Title string `json:"title,omitempty"`
	// The description of the policy.
	Description string `json:"description,omitempty"`
}
