/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents the details of a tender with `type` `BUY_NOW_PAY_LATER`.
type TenderBuyNowPayLaterDetails struct {
	BuyNowPayLaterBrand *TenderBuyNowPayLaterDetailsBrand `json:"buy_now_pay_later_brand,omitempty"`
	Status *TenderBuyNowPayLaterDetailsStatus `json:"status,omitempty"`
}
