/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square
// FulfillmentPickupDetailsScheduleType : The schedule type of the pickup fulfillment.
type FulfillmentPickupDetailsScheduleType string

// List of FulfillmentPickupDetailsScheduleType
const (
	SCHEDULED_FulfillmentPickupDetailsScheduleType FulfillmentPickupDetailsScheduleType = "SCHEDULED"
	ASAP_FulfillmentPickupDetailsScheduleType FulfillmentPickupDetailsScheduleType = "ASAP"
)
