/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Fields to describe the action that displays QR-Codes.
type QrCodeOptions struct {
	// The title text to display in the QR code flow on the Terminal.
	Title string `json:"title"`
	// The body text to display in the QR code flow on the Terminal.
	Body string `json:"body"`
	// The text representation of the data to show in the QR code as UTF8-encoded data.
	BarcodeContents string `json:"barcode_contents"`
}
