/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TenderSquareAccountDetailsStatus string

// List of TenderSquareAccountDetailsStatus
const (
	AUTHORIZED_TenderSquareAccountDetailsStatus TenderSquareAccountDetailsStatus = "AUTHORIZED"
	CAPTURED_TenderSquareAccountDetailsStatus TenderSquareAccountDetailsStatus = "CAPTURED"
	VOIDED_TenderSquareAccountDetailsStatus TenderSquareAccountDetailsStatus = "VOIDED"
	FAILED_TenderSquareAccountDetailsStatus TenderSquareAccountDetailsStatus = "FAILED"
)
