/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The food and beverage-specific details of a `FOOD_AND_BEV` item.
type CatalogItemFoodAndBeverageDetails struct {
	// The calorie count (in the unit of kcal) for the `FOOD_AND_BEV` type of items.
	CalorieCount int32 `json:"calorie_count,omitempty"`
	// The dietary preferences for the `FOOD_AND_BEV` item.
	DietaryPreferences []CatalogItemFoodAndBeverageDetailsDietaryPreference `json:"dietary_preferences,omitempty"`
	// The ingredients for the `FOOD_AND_BEV` type item.
	Ingredients []CatalogItemFoodAndBeverageDetailsIngredient `json:"ingredients,omitempty"`
}
