/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// The summary of a closed cash drawer shift. This model contains only the money counted to start a cash drawer shift, counted at the end of the shift, and the amount that should be in the drawer at shift end based on summing all cash drawer shift events.
type CashDrawerShiftSummary struct {
	// The shift unique ID.
	Id string `json:"id,omitempty"`
	State *CashDrawerShiftState `json:"state,omitempty"`
	// The shift start time in ISO 8601 format.
	OpenedAt string `json:"opened_at,omitempty"`
	// The shift end time in ISO 8601 format.
	EndedAt string `json:"ended_at,omitempty"`
	// The shift close time in ISO 8601 format.
	ClosedAt string `json:"closed_at,omitempty"`
	// An employee free-text description of a cash drawer shift.
	Description string `json:"description,omitempty"`
	OpenedCashMoney *Money `json:"opened_cash_money,omitempty"`
	ExpectedCashMoney *Money `json:"expected_cash_money,omitempty"`
	ClosedCashMoney *Money `json:"closed_cash_money,omitempty"`
	// The shift start time in RFC 3339 format.
	CreatedAt string `json:"created_at,omitempty"`
	// The shift updated at time in RFC 3339 format.
	UpdatedAt string `json:"updated_at,omitempty"`
	// The ID of the location the cash drawer shift belongs to.
	LocationId string `json:"location_id,omitempty"`
}
