/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type CheckoutLocationSettingsBrandingHeaderType string

// List of CheckoutLocationSettingsBrandingHeaderType
const (
	BUSINESS_NAME_CheckoutLocationSettingsBrandingHeaderType CheckoutLocationSettingsBrandingHeaderType = "BUSINESS_NAME"
	FRAMED_LOGO_CheckoutLocationSettingsBrandingHeaderType CheckoutLocationSettingsBrandingHeaderType = "FRAMED_LOGO"
	FULL_WIDTH_LOGO_CheckoutLocationSettingsBrandingHeaderType CheckoutLocationSettingsBrandingHeaderType = "FULL_WIDTH_LOGO"
)
