/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// V1OrderHistoryEntry
type V1OrderHistoryEntry struct {
	Action *V1OrderHistoryEntryAction `json:"action,omitempty"`
	// The time when the action was performed, in ISO 8601 format.
	CreatedAt string `json:"created_at,omitempty"`
}
