/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Describes receipt action fields.
type ReceiptOptions struct {
	// The reference to the Square payment ID for the receipt.
	PaymentId string `json:"payment_id"`
	// Instructs the device to print the receipt without displaying the receipt selection screen. Requires `printer_enabled` set to true. Defaults to false.
	PrintOnly bool `json:"print_only,omitempty"`
	// Identify the receipt as a reprint rather than an original receipt. Defaults to false.
	IsDuplicate bool `json:"is_duplicate,omitempty"`
}
