/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DeviceAttributes struct {
	Type_ *DeviceAttributesDeviceType `json:"type"`
	// The maker of the device.
	Manufacturer string `json:"manufacturer"`
	// The specific model of the device.
	Model string `json:"model,omitempty"`
	// A seller-specified name for the device.
	Name string `json:"name,omitempty"`
	// The manufacturer-supplied identifier for the device (where available). In many cases, this identifier will be a serial number.
	ManufacturersId string `json:"manufacturers_id,omitempty"`
	// The RFC 3339-formatted value of the most recent update to the device information. (Could represent any field update on the device.)
	UpdatedAt string `json:"updated_at,omitempty"`
	// The current version of software installed on the device.
	Version string `json:"version,omitempty"`
	// The merchant_token identifying the merchant controlling the device.
	MerchantToken string `json:"merchant_token,omitempty"`
}
