/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Represents a [CreateInvoiceAttachment]($e/Invoices/CreateInvoiceAttachment) request.
type CreateInvoiceAttachmentRequest struct {
	// A unique string that identifies the `CreateInvoiceAttachment` request. For more information, see [Idempotency](https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency).
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// The description of the attachment to display on the invoice.
	Description string `json:"description,omitempty"`
}
