/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents the details of a tender with `type` `SQUARE_ACCOUNT`.
type TenderSquareAccountDetails struct {
	Status *TenderSquareAccountDetailsStatus `json:"status,omitempty"`
}
