/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents an action as a pending change to a subscription.
type SubscriptionAction struct {
	// The ID of an action scoped to a subscription.
	Id string `json:"id,omitempty"`
	Type_ *SubscriptionActionType `json:"type,omitempty"`
	// The `YYYY-MM-DD`-formatted date when the action occurs on the subscription.
	EffectiveDate string `json:"effective_date,omitempty"`
	// The new billing anchor day value, for a `CHANGE_BILLING_ANCHOR_DATE` action.
	MonthlyBillingAnchorDate int32 `json:"monthly_billing_anchor_date,omitempty"`
	// A list of Phases, to pass phase-specific information used in the swap.
	Phases []Phase `json:"phases,omitempty"`
	// The target subscription plan variation that a subscription switches to, for a `SWAP_PLAN` action.
	NewPlanVariationId string `json:"new_plan_variation_id,omitempty"`
}
