/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details about a refund's destination.
type DestinationDetails struct {
	CardDetails *DestinationDetailsCardRefundDetails `json:"card_details,omitempty"`
	CashDetails *DestinationDetailsCashRefundDetails `json:"cash_details,omitempty"`
	ExternalDetails *DestinationDetailsExternalRefundDetails `json:"external_details,omitempty"`
}
