/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square
// LoyaltyPromotionStatus : Indicates the status of a [loyalty promotion]($m/LoyaltyPromotion).
type LoyaltyPromotionStatus string

// List of LoyaltyPromotionStatus
const (
	ACTIVE_LoyaltyPromotionStatus LoyaltyPromotionStatus = "ACTIVE"
	ENDED_LoyaltyPromotionStatus LoyaltyPromotionStatus = "ENDED"
	CANCELED_LoyaltyPromotionStatus LoyaltyPromotionStatus = "CANCELED"
	SCHEDULED_LoyaltyPromotionStatus LoyaltyPromotionStatus = "SCHEDULED"
)
