/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Defines output parameters in a response from the  [ResumeSubscription]($e/Subscriptions/ResumeSubscription) endpoint.
type ResumeSubscriptionResponse struct {
	// Errors encountered during the request.
	Errors []ModelError `json:"errors,omitempty"`
	Subscription *Subscription `json:"subscription,omitempty"`
	// A list of `RESUME` actions created by the request and scheduled for the subscription.
	Actions []SubscriptionAction `json:"actions,omitempty"`
}
