/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Defines input parameters in a request to the [ChangeBillingAnchorDate]($e/Subscriptions/ChangeBillingAnchorDate) endpoint.
type ChangeBillingAnchorDateRequest struct {
	// The anchor day for the billing cycle.
	MonthlyBillingAnchorDate int32 `json:"monthly_billing_anchor_date,omitempty"`
	// The `YYYY-MM-DD`-formatted date when the scheduled `BILLING_ANCHOR_CHANGE` action takes place on the subscription.  When this date is unspecified or falls within the current billing cycle, the billing anchor date is changed immediately.
	EffectiveDate string `json:"effective_date,omitempty"`
}
