/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A value qualified by unit of measure.
type DeviceComponentDetailsMeasurement struct {
	Value int32 `json:"value,omitempty"`
}
