/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details about the customer making the payment.
type CustomerDetails struct {
	// Indicates whether the customer initiated the payment.
	CustomerInitiated bool `json:"customer_initiated,omitempty"`
	// Indicates that the seller keyed in payment details on behalf of the customer. This is used to flag a payment as Mail Order / Telephone Order (MOTO).
	SellerKeyedIn bool `json:"seller_keyed_in,omitempty"`
}
