/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square
// GiftCardActivityAdjustIncrementReason : Indicates the reason for adding money to a [gift card]($m/GiftCard).
type GiftCardActivityAdjustIncrementReason string

// List of GiftCardActivityAdjustIncrementReason
const (
	COMPLIMENTARY_GiftCardActivityAdjustIncrementReason GiftCardActivityAdjustIncrementReason = "COMPLIMENTARY"
	SUPPORT_ISSUE_GiftCardActivityAdjustIncrementReason GiftCardActivityAdjustIncrementReason = "SUPPORT_ISSUE"
	TRANSACTION_VOIDED_GiftCardActivityAdjustIncrementReason GiftCardActivityAdjustIncrementReason = "TRANSACTION_VOIDED"
)
