/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// DeviceAttributesDeviceType : An enum identifier of the device type.
type DeviceAttributesDeviceType string

// List of DeviceAttributesDeviceType
const (
	TERMINAL_DeviceAttributesDeviceType DeviceAttributesDeviceType = "TERMINAL"
)
