/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type ConfirmationOptions struct {
	// The title text to display in the confirmation screen flow on the Terminal.
	Title string `json:"title"`
	// The agreement details to display in the confirmation flow on the Terminal.
	Body string `json:"body"`
	// The button text to display indicating the customer agrees to the displayed terms.
	AgreeButtonText string `json:"agree_button_text"`
	// The button text to display indicating the customer does not agree to the displayed terms.
	DisagreeButtonText string `json:"disagree_button_text,omitempty"`
	Decision *ConfirmationDecision `json:"decision,omitempty"`
}
