/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square
// SearchEventsSortField : Specifies the sort key for events returned from a search.
type SearchEventsSortField string

// List of SearchEventsSortField
const (
	DEFAULT__SearchEventsSortField SearchEventsSortField = "DEFAULT"
)
