/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DataCollectionOptions struct {
	// The title text to display in the data collection flow on the Terminal.
	Title string `json:"title"`
	// The body text to display under the title in the data collection screen flow on the Terminal.
	Body string `json:"body"`
	InputType *DataCollectionOptionsInputType `json:"input_type"`
	CollectedData *CollectedData `json:"collected_data,omitempty"`
}
