/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckoutLocationSettings struct {
	// The ID of the location that these settings apply to.
	LocationId string `json:"location_id,omitempty"`
	// Indicates whether customers are allowed to leave notes at checkout.
	CustomerNotesEnabled bool `json:"customer_notes_enabled,omitempty"`
	// Policy information is displayed at the bottom of the checkout pages. You can set a maximum of two policies.
	Policies []CheckoutLocationSettingsPolicy `json:"policies,omitempty"`
	Branding *CheckoutLocationSettingsBranding `json:"branding,omitempty"`
	Tipping *CheckoutLocationSettingsTipping `json:"tipping,omitempty"`
	Coupons *CheckoutLocationSettingsCoupons `json:"coupons,omitempty"`
	// The timestamp when the settings were last updated, in RFC 3339 format. Examples for January 25th, 2020 6:25:34pm Pacific Standard Time: UTC: 2020-01-26T02:25:34Z Pacific Standard Time with UTC offset: 2020-01-25T18:25:34-08:00
	UpdatedAt string `json:"updated_at,omitempty"`
}
