/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type V1OrderState string

// List of V1OrderState
const (
	PENDING_V1OrderState V1OrderState = "PENDING"
	OPEN_V1OrderState V1OrderState = "OPEN"
	COMPLETED_V1OrderState V1OrderState = "COMPLETED"
	CANCELED_V1OrderState V1OrderState = "CANCELED"
	REFUNDED_V1OrderState V1OrderState = "REFUNDED"
	REJECTED_V1OrderState V1OrderState = "REJECTED"
)
