/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents details about a `REFUND` [gift card activity type]($m/GiftCardActivityType).
type GiftCardActivityRefund struct {
	// The ID of the refunded `REDEEM` gift card activity. Square populates this field if the  `payment_id` in the corresponding [RefundPayment](api-endpoint:Refunds-RefundPayment) request  represents a gift card redemption.  For applications that use a custom payment processing system, this field is required when creating a `REFUND` activity. The provided `REDEEM` activity ID must be linked to the same gift card.
	RedeemActivityId string `json:"redeem_activity_id,omitempty"`
	AmountMoney *Money `json:"amount_money,omitempty"`
	// A client-specified ID that associates the gift card activity with an entity in another system.
	ReferenceId string `json:"reference_id,omitempty"`
	// The ID of the refunded payment. Square populates this field if the refund is for a  payment processed by Square. This field matches the `payment_id` in the corresponding [RefundPayment](api-endpoint:Refunds-RefundPayment) request.
	PaymentId string `json:"payment_id,omitempty"`
}
