/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Represents the sorting criteria in a [search query]($m/CustomerQuery) that defines how to sort customer profiles returned in [SearchCustomers]($e/Customers/SearchCustomers) results.
type CustomerSort struct {
	Field *CustomerSortField `json:"field,omitempty"`
	Order *SortOrder `json:"order,omitempty"`
}
