/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Defines output parameters in a response of the [BulkSwapPlan]($e/Subscriptions/BulkSwapPlan) endpoint.
type BulkSwapPlanResponse struct {
	// Errors encountered during the request.
	Errors []ModelError `json:"errors,omitempty"`
	// The number of affected subscriptions.
	AffectedSubscriptions int32 `json:"affected_subscriptions,omitempty"`
}
