/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Defines a sorter used to sort results from [SearchVendors]($e/Vendors/SearchVendors).
type SearchVendorsRequestSort struct {
	Field *SearchVendorsRequestSortField `json:"field,omitempty"`
	Order *SortOrder `json:"order,omitempty"`
}
