/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EventData struct {
	// The name of the affected object’s type.
	Type_ string `json:"type,omitempty"`
	// The ID of the affected object.
	Id string `json:"id,omitempty"`
	// This is true if the affected object has been deleted; otherwise, it's absent.
	Deleted bool `json:"deleted,omitempty"`
	// An object containing fields and values relevant to the event. It is absent if the affected object has been deleted.
	Object *interface{} `json:"object,omitempty"`
}
