/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square
// GiftCardActivityBlockReason : Indicates the reason for blocking a [gift card]($m/GiftCard).
type GiftCardActivityBlockReason string

// List of GiftCardActivityBlockReason
const (
	CHARGEBACK_BLOCK_GiftCardActivityBlockReason GiftCardActivityBlockReason = "CHARGEBACK_BLOCK"
)
