/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// FulfillmentState : The current state of this fulfillment.
type FulfillmentState string

// List of FulfillmentState
const (
	PROPOSED_FulfillmentState FulfillmentState = "PROPOSED"
	RESERVED_FulfillmentState FulfillmentState = "RESERVED"
	PREPARED_FulfillmentState FulfillmentState = "PREPARED"
	COMPLETED_FulfillmentState FulfillmentState = "COMPLETED"
	CANCELED_FulfillmentState FulfillmentState = "CANCELED"
	FAILED_FulfillmentState FulfillmentState = "FAILED"
)
