/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Location-specific overrides for specified properties of a `CatalogModifier` object.
type ModifierLocationOverrides struct {
	// The ID of the `Location` object representing the location. This can include a deactivated location.
	LocationId string `json:"location_id,omitempty"`
	PriceMoney *Money `json:"price_money,omitempty"`
	// Indicates whether the modifier is sold out at the specified location or not. As an example, for cheese (modifier) burger (item), when the modifier is sold out, it is the cheese, but not the burger, that is sold out. The seller can manually set this sold out status. Attempts by an application to set this attribute are ignored.
	SoldOut bool `json:"sold_out,omitempty"`
}
