/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckoutLocationSettingsCoupons struct {
	// Indicates whether coupons are enabled for this location.
	Enabled bool `json:"enabled,omitempty"`
}
