/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

type DeviceComponentDetailsApplicationDetails struct {
	ApplicationType *ApplicationType `json:"application_type,omitempty"`
	// The version of the application.
	Version string `json:"version,omitempty"`
	// The location_id of the session for the application.
	SessionLocation string `json:"session_location,omitempty"`
	// The id of the device code that was used to log in to the device.
	DeviceCodeId string `json:"device_code_id,omitempty"`
}
