/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// V1Order
type V1Order struct {
	// Any errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
	// The order's unique identifier.
	Id string `json:"id,omitempty"`
	// The email address of the order's buyer.
	BuyerEmail string `json:"buyer_email,omitempty"`
	// The name of the order's buyer.
	RecipientName string `json:"recipient_name,omitempty"`
	// The phone number to use for the order's delivery.
	RecipientPhoneNumber string `json:"recipient_phone_number,omitempty"`
	State *V1OrderState `json:"state,omitempty"`
	ShippingAddress *Address `json:"shipping_address,omitempty"`
	SubtotalMoney *V1Money `json:"subtotal_money,omitempty"`
	TotalShippingMoney *V1Money `json:"total_shipping_money,omitempty"`
	TotalTaxMoney *V1Money `json:"total_tax_money,omitempty"`
	TotalPriceMoney *V1Money `json:"total_price_money,omitempty"`
	TotalDiscountMoney *V1Money `json:"total_discount_money,omitempty"`
	// The time when the order was created, in ISO 8601 format.
	CreatedAt string `json:"created_at,omitempty"`
	// The time when the order was last modified, in ISO 8601 format.
	UpdatedAt string `json:"updated_at,omitempty"`
	// The time when the order expires if no action is taken, in ISO 8601 format.
	ExpiresAt string `json:"expires_at,omitempty"`
	// The unique identifier of the payment associated with the order.
	PaymentId string `json:"payment_id,omitempty"`
	// A note provided by the buyer when the order was created, if any.
	BuyerNote string `json:"buyer_note,omitempty"`
	// A note provided by the merchant when the order's state was set to COMPLETED, if any
	CompletedNote string `json:"completed_note,omitempty"`
	// A note provided by the merchant when the order's state was set to REFUNDED, if any.
	RefundedNote string `json:"refunded_note,omitempty"`
	// A note provided by the merchant when the order's state was set to CANCELED, if any.
	CanceledNote string `json:"canceled_note,omitempty"`
	Tender *V1Tender `json:"tender,omitempty"`
	// The history of actions associated with the order.
	OrderHistory []V1OrderHistoryEntry `json:"order_history,omitempty"`
	// The promo code provided by the buyer, if any.
	PromoCode string `json:"promo_code,omitempty"`
	// For Bitcoin transactions, the address that the buyer sent Bitcoin to.
	BtcReceiveAddress string `json:"btc_receive_address,omitempty"`
	// For Bitcoin transactions, the price of the buyer's order in satoshi (100 million satoshi equals 1 BTC).
	BtcPriceSatoshi float64 `json:"btc_price_satoshi,omitempty"`
}
