/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DeviceComponentDetailsWiFiDetails struct {
	// A boolean to represent whether the WiFI interface is currently active.
	Active bool `json:"active,omitempty"`
	// The name of the connected WIFI network.
	Ssid string `json:"ssid,omitempty"`
	// The string representation of the device’s IPv4 address.
	IpAddressV4 string `json:"ip_address_v4,omitempty"`
	// The security protocol for a secure connection (e.g. WPA2). None provided if the connection is unsecured.
	SecureConnection string `json:"secure_connection,omitempty"`
	SignalStrength *DeviceComponentDetailsMeasurement `json:"signal_strength,omitempty"`
}
