/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// CatalogModifierListModifierType : Defines the type of `CatalogModifierList`.
type CatalogModifierListModifierType string

// List of CatalogModifierListModifierType
const (
	LIST_CatalogModifierListModifierType CatalogModifierListModifierType = "LIST"
	TEXT_CatalogModifierListModifierType CatalogModifierListModifierType = "TEXT"
)
