/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Defines input parameters in a request to the  [UpdateSubscription]($e/Subscriptions/UpdateSubscription) endpoint.
type UpdateSubscriptionRequest struct {
	Subscription *Subscription `json:"subscription,omitempty"`
}
