/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Stores details about a cash refund. Contains only non-confidential information.
type DestinationDetailsCashRefundDetails struct {
	SellerSuppliedMoney *Money `json:"seller_supplied_money"`
	ChangeBackMoney *Money `json:"change_back_money,omitempty"`
}
