/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckoutLocationSettingsBrandingButtonShape string

// List of CheckoutLocationSettingsBrandingButtonShape
const (
	SQUARED_CheckoutLocationSettingsBrandingButtonShape CheckoutLocationSettingsBrandingButtonShape = "SQUARED"
	ROUNDED_CheckoutLocationSettingsBrandingButtonShape CheckoutLocationSettingsBrandingButtonShape = "ROUNDED"
	PILL_CheckoutLocationSettingsBrandingButtonShape CheckoutLocationSettingsBrandingButtonShape = "PILL"
)
