/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// LoyaltyPromotionTriggerLimitInterval : Indicates the time period that the [trigger limit]($m/LoyaltyPromotionTriggerLimit) applies to, which is used to determine the number of times a buyer can earn points for a [loyalty promotion]($m/LoyaltyPromotion).
type LoyaltyPromotionTriggerLimitInterval string

// List of LoyaltyPromotionTriggerLimitInterval
const (
	ALL_TIME_LoyaltyPromotionTriggerLimitInterval LoyaltyPromotionTriggerLimitInterval = "ALL_TIME"
	DAY_LoyaltyPromotionTriggerLimitInterval LoyaltyPromotionTriggerLimitInterval = "DAY"
)
