/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square

// Filter based on [order fulfillment]($m/Fulfillment) information.
type SearchOrdersFulfillmentFilter struct {
	// A list of [fulfillment types](entity:FulfillmentType) to filter for. The list returns orders if any of its fulfillments match any of the fulfillment types listed in this field. See [FulfillmentType](#type-fulfillmenttype) for possible values
	FulfillmentTypes []FulfillmentType `json:"fulfillment_types,omitempty"`
	// A list of [fulfillment states](entity:FulfillmentState) to filter for. The list returns orders if any of its fulfillments match any of the fulfillment states listed in this field. See [FulfillmentState](#type-fulfillmentstate) for possible values
	FulfillmentStates []FulfillmentState `json:"fulfillment_states,omitempty"`
}
