/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package square
// InvoiceAutomaticPaymentSource : Indicates the automatic payment method for an [invoice payment request]($m/InvoicePaymentRequest).
type InvoiceAutomaticPaymentSource string

// List of InvoiceAutomaticPaymentSource
const (
	NONE_InvoiceAutomaticPaymentSource InvoiceAutomaticPaymentSource = "NONE"
	CARD_ON_FILE_InvoiceAutomaticPaymentSource InvoiceAutomaticPaymentSource = "CARD_ON_FILE"
	BANK_ON_FILE_InvoiceAutomaticPaymentSource InvoiceAutomaticPaymentSource = "BANK_ON_FILE"
)
