/*
 * Square
 *
 * Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents filtering and sorting criteria for a [SearchCustomers]($e/Customers/SearchCustomers) request.
type CustomerQuery struct {
	Filter *CustomerFilter `json:"filter,omitempty"`
	Sort *CustomerSort `json:"sort,omitempty"`
}
